### ISSUE TITLE
Crashes when using with Buildcraft 6.3.1

### ISSUE THREAD

**Issue by Abestanis** [da3dsoul/Additional-Buildcraft-Objects-Mod#1]
Hi, I really like this mod and was really happy to see, that there is someone who not only just continues development, but also has added some quite cool new things which helps this mod to move further.

I myself as a developer appreciate the time and effort you put into maintaining this code and adding your own ideas. I just want you to know that there are people who use this mod and enjoy the outcome your hard work.

In this context, I want to ask you for an update for the newest buildcraft release. If you start minecraft with the latest buildcraft and your mod, you'll get a NoClassDefFoundError.
Can you please try to fix this issue, so we can continue to enjoy your great mod!

**Comment by da3dsoul** [comment]
I'll look into it. Also this fork is deprecated, please use the other repository.

**Comment by da3dsoul** [comment]
https://github.com/da3dsoul/Additional-Buildcraft-Objects 
Go to release section and download it. place it in the mods folder.
